builds:
- main: .
  ldflags: 
    - -s -w -X github.com/kekeniker/spa/pkg/version.Version={{.Tag}} -X github.com/kekeniker/spa/pkg/version.Revision={{.ShortCommit}} -X github.com/kekeniker/spa/pkg/version.BuildDate={{.Date}}
  goos:
  - linux
  - darwin
  - windows
brews:
  - tap:
      owner: kekeniker
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url_template: "https://github.com/kekeniker/spa/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    folder: Formula
    description: "Spinnaker Admin tools"
    homepage: "https://github.com/kekeniker/spa"
    test: |
      system "#{bin}/spa --version"
dockers:
  - image_templates:
      - "ghcr.io/kekeniker/spa:{{ .Tag }}"
      - "ghcr.io/kekeniker/spa:v{{ .Major }}"
      - "ghcr.io/kekeniker/spa:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/kekeniker/spa:latest"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    dockerfile: Dockerfile.compile
    binaries:
      - spa
